import dotenv from 'dotenv';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const configDir = path.dirname(fileURLToPath(import.meta.url));
const backendDir = path.resolve(configDir, '../..');
const projectRoot = path.resolve(backendDir, '..');

process.env.PROJECT_ROOT ||= projectRoot;
process.env.BACKEND_DIR ||= backendDir;
dotenv.config({ path: path.join(projectRoot, '.env'), override: false });
dotenv.config({ path: path.join(backendDir, '.env'), override: false });

process.env.OPENROUTER_BASE_URL ||= 'https://openrouter.ai/api/v1';
process.env.OPENROUTER_ANALYSIS_MODEL ||= '';
process.env.OPENROUTER_IMAGE_MODEL ||= 'google/gemini-3.1-flash-image-preview';
process.env.OPENROUTER_SAFETY_MODEL ||= 'nvidia/nemotron-3.5-content-safety:free';
process.env.OPENROUTER_IMAGE_QUALITY ||= 'high';
process.env.OPENROUTER_IMAGE_SIZE ||= '1K';
process.env.OPENROUTER_REASONING_EFFORT ||= 'medium';
process.env.OPENROUTER_BACKGROUND_MODE ||= 'transparent';
process.env.OPENROUTER_SAFETY_ENABLED ||= '1';
process.env.OPENROUTER_APP_NAME ||= 'Design Mudah Vector';
process.env.LOGO_RESTORE_ENABLED ||= '1';
process.env.LOGO_RESTORE_STRICT_SPOTS ||= '1';
process.env.TRACE_SMOOTH_ENABLED ||= '1';
process.env.TRACE_SMOOTH_SIGMA ||= '0.7';
process.env.TRACE_SMOOTH_THRESHOLD ||= '180';
process.env.TRACE_CURVE_CLEANUP_ENABLED ||= '1';
process.env.TRACE_CURVE_MORPH_RADIUS ||= '1';
process.env.TRACE_CURVE_MORPH_ITERATIONS ||= '1';
process.env.TRACE_CURVE_RESAMPLE_SCALE ||= '0.65';
process.env.TRACE_CURVE_SMOOTH_SIGMA ||= '0.85';
process.env.TRACE_CURVE_SMOOTH_THRESHOLD ||= '180';
process.env.TRACE_CURVE_TURD_SIZE ||= '12';
process.env.TRACE_CURVE_ALPHA_MAX ||= '1.25';
process.env.TRACE_CURVE_OPT_TOLERANCE ||= '0.32';
process.env.TRACE_CURVE_FLOAT_PRECISION ||= '1';
process.env.AI_REDRAW_PRESET ||= 'quality';
process.env.SUPABASE_PUBLISHABLE_KEY ||= process.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
